---
 - name: java install and update
   hosts: aws_host
   become: true
  
   tasks:

      - name: "installing java"
        apt:
            name: "openjdk-8-jdk"
            state: present
            update_cache: yes

      - name: "adding path to java"
        alternatives:
            name: java
            link: /usr/bin/java
            path: /usr/lib/jvm/java-8-openjdk-amd64/bin/java      

      - name: "checking java version"
        shell:
            cmd: java -version    