---
 - name: Create an ec2
   hosts: local
   connection: local

   tasks:
    - name: Create ec2 instance
      ec2:
        key_name: awskeypair
        instance_type: t2.micro
        region: us-east-2
        image: ami-08962a4068733a2b6
        wait: yes
        count: 1
        instance_tags:
           Name: ubuntuvm
        vpc_subnet_id: subnet-34cd8478
        assign_public_ip: yes